import Head from 'next/head'
import Layout from '../components/layout/layout';

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Home🌞</h1>
      </div>
    </Layout>
  )
}
